/* Packages */
import { getFallbacks, getFavicons, getFonts, getSettings } from '@displaycoffee/tokens';

/* Scripts */
import themeJson from '@/_core/tokens/theme.json' with { type: 'json' }; // generated by tokens-generate (@displaycoffee/tokens)

/* Build the head favicons, theme colors, font preloads and font-face styles from the project's theme.json */
/* Note: site details (title, description, url) come from WordPress in Head.astro */
export const createHead = () => {
	const colors = (themeJson.color ?? {}) as Record<string, string | boolean>;
	const fallbacks = getFallbacks(themeJson);
	const favicons = getFavicons(themeJson);
	const fonts = getFonts(themeJson);
	const settings = getSettings(themeJson);

	const head = {
		format: {
			emptyLines: (value: string) => {
				// Remove empty lines
				return value.replace(/^\s*[\r\n]/gm, '');
			},
			styles: (value: string) => {
				// Format style block by removing the indentation shared by every line, so nested rules keep their relative indent
				const lines = head.format.emptyLines(value).split('\n');
				const indents = lines.filter((line) => line.trim()).map((line) => (line.match(/^[ \t]*/) ?? [''])[0].length);
				const minIndent = indents.length ? Math.min(...indents) : 0;
				return lines.map((line) => line.slice(minIndent)).join('\n');
			},
		},
		data: {
			favicons: () => {
				// Favicons from the favicon tokens
				return favicons
					.filter((favicon) => favicon.isHead)
					.map((favicon) => ({ rel: favicon.rel, sizes: favicon.size, type: favicon.type, url: favicon.src }));
			},
			themeColors: () => {
				// Theme color for the browser UI
				// Note: when the OS setting can switch themes, each theme gets its own color (falling back to bg if there's no alternate bg token)
				// Otherwise, or when both colors match, the default theme's color is always used
				const bg = typeof colors.bg === 'string' ? colors.bg : '';
				const alternateBg = colors[`bg-${settings.theme.alternate}`];
				const themeColors: Record<string, string> = {
					[settings.theme.default]: bg,
					[settings.theme.alternate]: typeof alternateBg === 'string' ? alternateBg : bg,
				};

				if (!settings.theme.system || themeColors.light == themeColors.dark) {
					return [{ color: bg, media: undefined }];
				}
				return ['light', 'dark'].map((theme) => ({ color: themeColors[theme], media: `(prefers-color-scheme: ${theme})` }));
			},
			fontsPreload: () => {
				// Preload fonts
				return fonts
					.filter((font) => font.isPreload)
					.map((font) => ({ as: 'font', crossOrigin: 'anonymous', type: `font/${font.ext}`, url: font.src }));
			},
		},
		styles: {
			fallbacks: () => {
				// Build style string of font-face rules for fallback fonts
				const styles = fallbacks
					.map((fallback) => {
						return `
							@font-face {
								font-family: '${fallback.family}';
								src: ${fallback.src};
								size-adjust: ${fallback.size};
							}
						`;
					})
					.join('');
				return head.format.styles(styles);
			},
			fonts: () => {
				// Build style string of font-face rules for theme fonts
				const styles = fonts
					.map((font) => {
						const src = font.isLocal ? `${font.src}` : `url('${font.src}') format('${font.ext}')`;
						return `
							@font-face {
								font-family: '${font.family}';
								src: ${src};
								font-weight: ${font.weight};
								font-style: ${font.style};
								font-display: ${font.display};
							}
						`;
					})
					.join('');
				return head.format.styles(styles);
			},
		},
	};

	return head;
};
